# Generated by Django 3.2.9 on 2021-12-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lg_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaged', models.CharField(max_length=255)),
                ('modeld', models.CharField(max_length=255)),
                ('named', models.CharField(max_length=255)),
                ('disd', models.CharField(max_length=255)),
                ('sized', models.CharField(max_length=255)),
                ('colord', models.CharField(max_length=255)),
                ('categ', models.CharField(max_length=255)),
            ],
        ),
    ]
